AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Branch:
    Description: branch being deployed
    Type: String
  DeployEnv:
    Description: environment to deploy to
    Type: String
  ApiUrl:
    Description: API Url for custom domain and DNS record set
    Type: String
  StateApiName:
    Description: State API Lambda function name
    Type: String
  WhiskyApiName:
    Description: Whisky API Lambda function name
    Type: String
  HostedZoneId:
    Description: Hosted zone id
    Type: String
  ApiCertificateId:
    Description: Certificate id for API
    Type: String

Resources:
  StateAPIRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                Resource: "arn:aws:logs:*:*:*"
        -
          PolicyName: "statetable"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                Resource: !Sub
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${StateTable}"
                  - { StateTable: "states" }
        -
          PolicyName: "ssm"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
  StateAPIPolicy:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "StateAPIRole"
  StateAPIFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: aseaman-lambda-functions
        S3Key: !Join
          - ''
          - - !Ref DeployEnv
            - '/'
            - !Ref StateApiName
            - '.zip'
      Description: State API Lambda function
      FunctionName: !Ref StateApiName
      Handler: lambda_handler.lambda_handler
      Role : !GetAtt StateAPIRole.Arn
      Runtime: python3.6
      Timeout: 10
  StateAPIPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName:
        Fn::GetAtt:
          - StateAPIFunction
          - Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - Ref: "RestAPI"
            - "/*"
  WhiskyAPIRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                Resource: "arn:aws:logs:*:*:*"
        -
          PolicyName: "whisky-shelf-table"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:Scan"
                Resource: !Sub
                    - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${WhiskyTable}"
                    - { WhiskyTable: "whisky_shelf" }
        -
          PolicyName: "ssm"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
  WhiskyAPIPolicy:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "WhiskyAPIRole"
  WhiskyAPIFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: aseaman-lambda-functions
        S3Key: !Join
          - ''
          - - !Ref DeployEnv
            - '/'
            - !Ref WhiskyApiName
            - '.zip'
      Description: Lambda function for Whisky API
      FunctionName: !Ref WhiskyApiName
      Handler: lambda_handler.lambda_handler
      Role : !GetAtt WhiskyAPIRole.Arn
      Runtime: python3.6
      Timeout: 10
  WhiskyAPIPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName:
        Fn::GetAtt:
          - WhiskyAPIFunction
          - Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - Ref: "RestAPI"
            - "/*"

  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        Fn::Join:
          - ""
          - - "aseaman-website-api-"
            - !Ref DeployEnv
            - "-"
            - !Ref Branch

  StateAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestAPI
      ParentId:
        Fn::GetAtt:
          - RestAPI
          - RootResourceId
      PathPart: state_check
  StateAPIGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: StateAPIResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - StateAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: "{\"fun\": \"getUser\", \"parameters\": {\"userId\": \"$input.params('userId')\"}}"
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 404
  StateAPIPostMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: StateAPIResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - StateAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 404
  StateAPIOptionsMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: StateAPIResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - StateAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 403
      - StatusCode: 404

  WhiskyAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestAPI
      ParentId:
        Fn::GetAtt:
          - RestAPI
          - RootResourceId
      PathPart: whisky
  WhiskyAPIGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: WhiskyAPIResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - WhiskyAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: "{\"fun\": \"getUser\", \"parameters\": {\"userId\": \"$input.params('userId')\"}}"
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 404
  WhiskyAPIPostMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: WhiskyAPIResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - WhiskyAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 404
  WhiskyAPIOptionsMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: WhiskyAPIResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - WhiskyAPIFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "$input.json('$.body')"
          StatusCode: 200
        - SelectionPattern: "^not found.*"
          ResponseTemplates:
            application/json: "{}"
          StatusCode: 404
        PassthroughBehavior: NEVER
      RequestParameters:
        method.request.path.userId: 'true'
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 403
      - StatusCode: 404

  RestAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - StateAPIGetMethod
      - StateAPIPostMethod
      - StateAPIOptionsMethod
      - WhiskyAPIGetMethod
      - WhiskyAPIPostMethod
      - WhiskyAPIOptionsMethod
    Properties:
      RestApiId:
        Ref: RestAPI
      StageName: test

  RestAPICustomDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      RegionalCertificateArn: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${ApiCertificateId}"
      DomainName: !Ref ApiUrl
      EndpointConfiguration:
        Types:
          - REGIONAL

  RestAPIBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: "v1"
      DomainName: !Ref RestAPICustomDomainName
      RestApiId: !Ref RestAPI
    DependsOn:
      - RestAPI

  RestAPIDNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref ApiUrl
      Type: A
      AliasTarget:
        DNSName: !GetAtt [RestAPICustomDomainName, RegionalDomainName]
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt [RestAPICustomDomainName, RegionalHostedZoneId]
      HostedZoneId: !Ref HostedZoneId

Outputs:
  ApiId:
    Value:
      Ref: RestAPI
  ApiUrl:
    Value:
      Ref: RestAPIDNSRecordSet

