AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaS3APIRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "lambda_authorizer"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: "arn:aws:s3:::aseaman-public-bucket"
  LambdaS3APIPolicy:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "LambdaS3APIRole"
  LambdaS3API:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: !Sub |
          import json

          def lambda_handler(event,context):
              return {
                  "isBase64Encoded": False,
                  "statusCode": 200,
                  "headers": {},
                  "multiValueHeaders": {},
                  "body": "Hello!!!"
              }

      Description: Lambda function to handle S3 stuff
      FunctionName: read_public_s3
      Handler: index.lambda_handler
      Role : !GetAtt LambdaS3APIRole.Arn
      Runtime: python3.6
      Timeout: 10
