const MEMORY_SIZE = 4096;
const INTERPRETER_SIZE = 512;

const DISPLAY_WIDTH = 64;
const DISPLAY_HEIGHT = 32;

// Dimensions of the native window
const WINDOW_WIDTH = 1024;
const WINDOW_HEIGHT = 512;

// For SDL_PIXELFORMAT_RGBA8888
const PIXEL_COLOR = 0x00FFFF00;
const PIXEL_ALPHA = 0x000000FF;

const MICROSECOND_DELAY = 1600;

module.exports = {
    MEMORY_SIZE,
    INTERPRETER_SIZE,
    DISPLAY_WIDTH,
    DISPLAY_HEIGHT,
    WINDOW_WIDTH,
    WINDOW_HEIGHT,
    PIXEL_COLOR,
    PIXEL_ALPHA,
    MICROSECOND_DELAY,
};
