name: andrewseaman35/aseaman
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.6
    - run: pip install -U pip
    - run: pip install awscli
    - run: gem install sass
    - run: npm update
    - run: npm install -g browserify
    - run: npm install -g uglify-js
    - run: npm install -g ./website/ --save-dev
    - run: export PATH=$PATH:${{ github.workspace }}/.local/bin
    - run: "./scripts/travis_env.sh"
    - run: make -C backend test_ci
    - run: "./scripts/"
    # services:
#       # This item has no matching transformer
#       docker:
